package storage

import (
	"context"
	"errors"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/steveyegge/beads/issueops"
)

// roleAccessorNames is the nine-strong capability surface every storage
// decorator has to answer for. It is written out rather than derived so that
// adding a tenth role to DoltStorage without deciding what each decorator
// does with it is a compile-or-test failure somewhere, not silence.
var roleAccessorNames = []string{
	"IssueLifecycle",
	"IssueReader",
	"IssueRelations",
	"Counter",
	"WorkspaceConfig",
	"StatsReporter",
	"Commenter",
	"ReadyClaimer",
	"BatchCloser",
	"DependencyEditor",
}

// TestHookFiringStoreDeclaresEveryRoleAccessor is the structural half of the
// decorator's conformance story.
//
// HookFiringStore embeds DoltStorage for pass-through, which means DELETING an
// accessor still compiles: the embedded interface supplies a promoted method
// with the same signature, the decorator silently hands back the inner store's
// surface, and every hook that surface should have fired stops firing. The
// compile-time `var _ interface{...}` blocks at the bottom of hook_decorator.go
// cannot see this — a promoted method satisfies them exactly as well as a
// declared one. Reflection can: the compiler reports a promoted method's
// implementation as living in "<autogenerated>".
func TestHookFiringStoreDeclaresEveryRoleAccessor(t *testing.T) {
	assertRoleAccessorsAreDeclared(t, reflect.TypeOf(&HookFiringStore{}))
}

// assertRoleAccessorsAreDeclared fails for any role accessor the type inherits
// from an embedded field instead of declaring itself. Exported so the telemetry
// package, which cannot be imported from here, has a sibling of the same shape;
// see internal/telemetry/role_accessor_decorator_test.go.
func assertRoleAccessorsAreDeclared(t *testing.T, decorator reflect.Type) {
	t.Helper()
	for _, name := range roleAccessorNames {
		method, ok := decorator.MethodByName(name)
		if !ok {
			t.Errorf("%s has no %s accessor at all", decorator, name)
			continue
		}
		file, _ := runtime.FuncForPC(method.Func.Pointer()).FileLine(method.Func.Pointer())
		if strings.Contains(file, "<autogenerated>") {
			t.Errorf("%s.%s is promoted from the embedded store, not declared on the decorator: "+
				"the decorator hands back the inner surface undecorated", decorator, name)
		}
	}
}

// roleAccessorStore is a DoltStorage whose only real methods are the nine role
// accessors, each answering with a distinguishable sentinel so a test can tell
// a decorated surface from a passed-through one.
type roleAccessorStore struct {
	DoltStorage
	lifecycle issueops.Lifecycle
	reader    issueops.Reader
	relations issueops.Relations
	counter   issueops.Counter
	settings  issueops.WorkspaceConfig
	stats     issueops.StatsReporter
	commenter issueops.Commenter
	claimer   issueops.ReadyClaimer
	closer    issueops.BatchCloser
	editor    issueops.DependencyEditor
	err       error
}

func newRoleAccessorStore() *roleAccessorStore {
	sentinel := &roleAccessorSentinel{}
	return &roleAccessorStore{
		lifecycle: sentinel,
		reader:    sentinel,
		relations: sentinel,
		counter:   sentinel,
		settings:  sentinel,
		stats:     sentinel,
		commenter: sentinel,
		claimer:   sentinel,
		closer:    sentinel,
		editor:    sentinel,
	}
}

func (s *roleAccessorStore) IssueLifecycle() (issueops.Lifecycle, error) { return s.lifecycle, s.err }
func (s *roleAccessorStore) IssueReader() (issueops.Reader, error)       { return s.reader, s.err }
func (s *roleAccessorStore) IssueRelations() (issueops.Relations, error) { return s.relations, s.err }
func (s *roleAccessorStore) Counter() (issueops.Counter, error)          { return s.counter, s.err }
func (s *roleAccessorStore) WorkspaceConfig() (issueops.WorkspaceConfig, error) {
	return s.settings, s.err
}
func (s *roleAccessorStore) StatsReporter() (issueops.StatsReporter, error) {
	return s.stats, s.err
}
func (s *roleAccessorStore) Commenter() (issueops.Commenter, error) { return s.commenter, s.err }
func (s *roleAccessorStore) ReadyClaimer() (issueops.ReadyClaimer, error) {
	return s.claimer, s.err
}
func (s *roleAccessorStore) BatchCloser() (issueops.BatchCloser, error) { return s.closer, s.err }
func (s *roleAccessorStore) DependencyEditor() (issueops.DependencyEditor, error) {
	return s.editor, s.err
}

// roleAccessorSentinel implements all nine roles at once. Nothing calls its
// methods; identity is the whole point.
type roleAccessorSentinel struct{}

func (*roleAccessorSentinel) Create(context.Context, issueops.CreateRequest) (issueops.CreateResult, error) {
	return issueops.CreateResult{}, nil
}
func (*roleAccessorSentinel) Update(context.Context, issueops.UpdateRequest) (issueops.UpdateResult, error) {
	return issueops.UpdateResult{}, nil
}
func (*roleAccessorSentinel) Close(context.Context, issueops.CloseRequest) (issueops.CloseResult, error) {
	return issueops.CloseResult{}, nil
}
func (*roleAccessorSentinel) Reopen(context.Context, issueops.ReopenRequest) (issueops.ReopenResult, error) {
	return issueops.ReopenResult{}, nil
}
func (*roleAccessorSentinel) Ready(context.Context, issueops.ReadyRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}
func (*roleAccessorSentinel) List(context.Context, issueops.ListRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}
func (*roleAccessorSentinel) Get(context.Context, issueops.GetRequest) (*issueops.IssueDetails, error) {
	return nil, nil
}
func (*roleAccessorSentinel) Related(context.Context, issueops.RelatedRequest) ([]*issueops.RelatedIssue, error) {
	return nil, nil
}
func (*roleAccessorSentinel) Count(context.Context, issueops.CountRequest) (issueops.CountResult, error) {
	return issueops.CountResult{}, nil
}
func (*roleAccessorSentinel) CountByGroup(context.Context, issueops.CountByGroupRequest) (issueops.CountByGroupResult, error) {
	return issueops.CountByGroupResult{}, nil
}
func (*roleAccessorSentinel) GetSetting(context.Context, issueops.GetSettingRequest) (issueops.SettingResult, error) {
	return issueops.SettingResult{}, nil
}
func (*roleAccessorSentinel) ListSettings(context.Context, issueops.ListSettingsRequest) (issueops.ListSettingsResult, error) {
	return issueops.ListSettingsResult{}, nil
}
func (*roleAccessorSentinel) SetSetting(context.Context, issueops.SetSettingRequest) (issueops.SetSettingResult, error) {
	return issueops.SetSettingResult{}, nil
}
func (*roleAccessorSentinel) UnsetSetting(context.Context, issueops.UnsetSettingRequest) (issueops.UnsetSettingResult, error) {
	return issueops.UnsetSettingResult{}, nil
}
func (*roleAccessorSentinel) Stats(context.Context, issueops.StatsRequest) (issueops.StatsResult, error) {
	return issueops.StatsResult{}, nil
}
func (*roleAccessorSentinel) AssigneeStats(context.Context, issueops.AssigneeStatsRequest) (issueops.StatsResult, error) {
	return issueops.StatsResult{}, nil
}
func (*roleAccessorSentinel) AddComment(context.Context, issueops.AddCommentRequest) (issueops.AddCommentResult, error) {
	return issueops.AddCommentResult{}, nil
}
func (*roleAccessorSentinel) ClaimNext(context.Context, issueops.ClaimNextRequest) (issueops.ClaimNextResult, error) {
	return issueops.ClaimNextResult{}, nil
}
func (*roleAccessorSentinel) CloseBatch(context.Context, issueops.CloseBatchRequest) (issueops.CloseBatchResult, error) {
	return issueops.CloseBatchResult{}, nil
}
func (*roleAccessorSentinel) AddDependencies(context.Context, issueops.AddDependenciesRequest) (issueops.AddDependenciesResult, error) {
	return issueops.AddDependenciesResult{}, nil
}
func (*roleAccessorSentinel) RemoveDependency(context.Context, issueops.RemoveDependencyRequest) (issueops.RemoveDependencyResult, error) {
	return issueops.RemoveDependencyResult{}, nil
}

// TestHookFiringStoreWrapsTheWriteRolesAndPassesTheReadsThrough is the
// behavioural half, and it catches what reflection cannot: an accessor that IS
// declared but reads `return h.inner.Commenter()`. That edit compiles, keeps
// satisfying DoltStorage, and silently stops every completion hook on that
// role.
//
// Five roles are asserted the OTHER way round on purpose. Reads fire no
// completion hooks, so IssueReader, IssueRelations, Counter and StatsReporter
// deliberately return the inner surface unwrapped (hook_issue_reader.go,
// hook_relations.go, hook_counter.go, hook_stats_reporter.go); WorkspaceConfig
// does too, and it is the one that is NOT a read — a settings write changes the
// workspace rather than a bead, so this decorator's issue-shaped hook
// vocabulary has nothing to hand a hook script (hook_workspace_config.go).
// This test pins all five as decisions rather than leaving them
// indistinguishable from the regression above.
func TestHookFiringStoreWrapsTheWriteRolesAndPassesTheReadsThrough(t *testing.T) {
	inner := newRoleAccessorStore()
	store := NewHookFiringStore(inner, nil)

	for _, test := range []struct {
		name    string
		got     func() (any, error)
		want    any
		wrapped bool
	}{
		{"IssueLifecycle", func() (any, error) { return store.IssueLifecycle() }, inner.lifecycle, true},
		{"Commenter", func() (any, error) { return store.Commenter() }, inner.commenter, true},
		{"ReadyClaimer", func() (any, error) { return store.ReadyClaimer() }, inner.claimer, true},
		{"BatchCloser", func() (any, error) { return store.BatchCloser() }, inner.closer, true},
		{"DependencyEditor", func() (any, error) { return store.DependencyEditor() }, inner.editor, true},
		{"IssueReader", func() (any, error) { return store.IssueReader() }, inner.reader, false},
		{"IssueRelations", func() (any, error) { return store.IssueRelations() }, inner.relations, false},
		{"Counter", func() (any, error) { return store.Counter() }, inner.counter, false},
		{"WorkspaceConfig", func() (any, error) { return store.WorkspaceConfig() }, inner.settings, false},
		{"StatsReporter", func() (any, error) { return store.StatsReporter() }, inner.stats, false},
	} {
		t.Run(test.name, func(t *testing.T) {
			surface, err := test.got()
			if err != nil {
				t.Fatalf("%s() error = %v", test.name, err)
			}
			same := surface == test.want
			switch {
			case test.wrapped && same:
				t.Fatalf("%s() returned the inner surface undecorated, so its completion hooks never fire", test.name)
			case !test.wrapped && !same:
				t.Fatalf("%s() = %T, want the inner surface unwrapped — reads fire no hooks", test.name, surface)
			}
		})
	}
}

// TestHookFiringStoreRoleAccessorsPropagateInnerErrors pins the other half of
// the recursion: an accessor that recurses must not swallow the inner store's
// refusal on the way back.
func TestHookFiringStoreRoleAccessorsPropagateInnerErrors(t *testing.T) {
	want := errors.New("inner refused")
	inner := newRoleAccessorStore()
	inner.err = want
	store := NewHookFiringStore(inner, nil)

	for _, test := range []struct {
		name string
		got  func() (any, error)
	}{
		{"IssueLifecycle", func() (any, error) { return store.IssueLifecycle() }},
		{"Commenter", func() (any, error) { return store.Commenter() }},
		{"ReadyClaimer", func() (any, error) { return store.ReadyClaimer() }},
		{"BatchCloser", func() (any, error) { return store.BatchCloser() }},
		{"DependencyEditor", func() (any, error) { return store.DependencyEditor() }},
		{"IssueReader", func() (any, error) { return store.IssueReader() }},
		{"IssueRelations", func() (any, error) { return store.IssueRelations() }},
		{"Counter", func() (any, error) { return store.Counter() }},
		{"WorkspaceConfig", func() (any, error) { return store.WorkspaceConfig() }},
		{"StatsReporter", func() (any, error) { return store.StatsReporter() }},
	} {
		t.Run(test.name, func(t *testing.T) {
			if _, err := test.got(); !errors.Is(err, want) {
				t.Fatalf("%s() error = %v, want %v", test.name, err, want)
			}
		})
	}
}
