package conformance

import "testing"

// roleContractCases is the role tier's dispatch table: every contract file's
// exported cases, in the order that file declares them, under the bundle field
// that supplies their fixture.
//
// Adding a case to a contract file means adding it here too, and
// TestRoleContractCasesCoverEveryContractCase is what says so — it parses this
// package for the Run functions that take a fixture and fails on any the table
// omits, duplicates or reorders. Without that guard a case added later would
// simply stop being part of what an external backend is held to, which is the
// suite-level shape of a test that cannot fail.
var roleContractCases = []roleContract{
	roleCases("BatchCloser", "BatchCloser()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BatchCloserFixture { return b.BatchCloser },
		RunBatchCloserOutcomesMirrorItemsIndexForIndex,
		RunBatchCloserPerItemRefusalIsAResultAndSurvivorsCommit,
		RunBatchCloserOutcomeSnapshotIsTheDocumentedShape,
		RunBatchCloserRequestValidationReturnsZeroResultAndChangesNothing,
		RunBatchCloserClaimFilterValueFailureIsARequestValidationFailure,
		RunBatchCloserBackendFailureReturnsNoOutcomes,
		RunBatchCloserIdempotentRecloseIsAPerItemSuccess,
		RunBatchCloserAllIdempotentBatchLandsNothing,
		RunBatchCloserDuplicateItemRecloseAtItsOwnIndex,
		RunBatchCloserWispItemClosesAndEarnsTheClaim,
		RunBatchCloserDurableHistoryNeverNamesAWisp,
		RunBatchCloserForceBypassesOnlyClosePolicy,
		RunBatchCloserClaimNextHydratesWhenSomethingClosed,
		RunBatchCloserClaimNextIsNilWhenNothingClosed,
		RunBatchCloserClaimNextIsNilWhenTheFrontIsEmpty,
		RunBatchCloserClaimNextSeesAnUnblockingFromItsOwnBatch,
		RunBatchCloserRecordsOneHistoryEntryForWhatLanded,
		RunBatchCloserAllRefusedBatchRecordsNoHistory,
		RunBatchCloserDoesNotMutateTheCallerRequest,
		RunBatchCloserSettlesTheDependersOfWhatItClosed,
	),

	roleCases("BatchCreator", "BatchCreator()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BatchCreatorFixture { return b.BatchCreator },
		RunBatchCreatorCreatesEveryItemAsOneAct,
		RunBatchCreatorRefusesEverythingWhenOneItemRefuses,
		RunBatchCreatorRejectsAnUnusableRequest,
		RunBatchCreatorRefusesACrossPlaneInBatchEdge,
		RunBatchCreatorLinksAnEarlierItemOfTheSameBatch,
		RunBatchCreatorRefusesAnAbsentEdgeTarget,
		RunBatchCreatorAcceptsAForeignEdgeTarget,
		RunBatchCreatorRecordsOneHistoryEntry,
		RunBatchCreatorRecordsNoHistoryForAnEphemeralBatch,
		RunBatchCreatorDoesNotMutateTheCallerRequest,
	),

	roleCases("BlockingAnnotator", "BlockingAnnotator()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BlockingAnnotatorFixture { return b.BlockingAnnotator },
		RunBlockingAnnotatorAnswersOnePerIDInRequestOrder,
		RunBlockingAnnotatorCollapsesRepeatedIDs,
		RunBlockingAnnotatorReportsOpenBlockersOnly,
		RunBlockingAnnotatorReportsTheInboundDirection,
		RunBlockingAnnotatorSeparatesParentFromBlockers,
		RunBlockingAnnotatorDropsAClosedParent,
		RunBlockingAnnotatorOrdersAndCollapsesEachList,
		RunBlockingAnnotatorCountsAnUnresolvableBlockerAsOpen,
		RunBlockingAnnotatorReadsBothPlanes,
		RunBlockingAnnotatorIgnoresNonBlockingEdgeTypes,
		RunBlockingAnnotatorAnnotatesAnAbsentIDBare,
		RunBlockingAnnotatorResolvesExactIDsOnly,
		RunBlockingAnnotatorReportsAtMostOneParent,
		RunBlockingAnnotatorAnswersAnEmptyRequest,
		RunBlockingAnnotatorRefusesAnEmptyID,
		RunBlockingAnnotatorLeavesTheRequestAlone,
		RunBlockingAnnotatorWritesNothing,
	),

	// One contract file covers both halves of workspace identity: the eight
	// Bootstrapper cases write it and the four InitVerifier ones read it, and
	// the fixture carries both roles because the write cases assert through the
	// read one.
	roleCases("Bootstrapper", "Bootstrapper() and InitVerifier()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BootstrapperFixture { return b.Bootstrapper },
		RunBootstrapperIdentifiesAFreshSubstrate,
		RunBootstrapperStoresThePrefixWithoutItsTrailingHyphen,
		RunBootstrapperRefusesAnIdentifiedSubstrate,
		RunBootstrapperRefusesASubstrateCarryingOnlyAPrefix,
		RunBootstrapperRefusesASubstrateCarryingOnlyAProjectID,
		RunBootstrapperRefusesAnInvalidRequestWithoutWriting,
		RunBootstrapperLeavesTheSubstrateUntouchedWhenItCannotComplete,
		RunBootstrapperRecordsAtMostOneHistoryEntry,
		RunInitVerifierAnswersEmptyForAnUnidentifiedSubstrate,
		RunInitVerifierReportsAPartialIdentityAsItStands,
		RunInitVerifierReportsAFailedReadAsAnError,
		RunInitVerifierWritesNothing,
	),

	roleCases("Claimer", "IssueClaimer()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ClaimerFixture { return b.Claimer },
		RunClaimerClaimsAnUnassignedOpenIssueAndAnswersTheBareRow,
		RunClaimerTakesAnOpenIssueTheActorAlreadyHolds,
		RunClaimerReclaimsItsOwnInProgressIssueWithoutWriting,
		RunClaimerAcceptsAConfiguredActiveStatusAndRefusesAConfiguredWipOne,
		RunClaimerTakesAPoolAssignedIssueButRefusesAForeignHolder,
		RunClaimerRefusesABuiltInIneligibleStatusWithTheStateThatRefusedIt,
		RunClaimerRefusesAWispIDAsNotFound,
		RunClaimerRefusesIncompleteRequestsAndAnAbsentIDWithoutTouchingState,
		RunClaimerGrantsALiveLeaseOnTheRowItWonAndLeavesARefusedOneAlone,
		RunClaimerStampsStartedAtOnceAcrossTheTwoWritesItChoosesBetween,
		RunClaimerRefusalMessagesCarryTheirFragments,
	),

	roleCases("Commenter", "Commenter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *CommenterFixture { return b.Commenter },
		RunCommenterStoresTextVerbatim,
		RunCommenterResultMirrorsTheStoredRow,
		RunCommenterCommentOnAWispLandsOnTheWispThread,
		RunCommenterRefusesAnIDOnNeitherPlane,
		RunCommenterRefusesAnEmptyIssueID,
		RunCommenterDoesNotResolvePrefixes,
		RunCommenterRecordsAtMostOneHistoryEntry,
		RunCommenterLeavesTheAnchorIssueUntouched,
		RunCommenterRefusesBlankText,
		RunCommenterRefusesAnEmptyAuthor,
		RunCommenterLeavesTheCallersRequestAlone,
	),

	roleCases("Counter", "Counter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *CounterFixture { return b.Counter },
		RunCounterCountsTheDurablePlaneByDefault,
		RunCounterIncludeInfraMergesTheWispTier,
		RunCounterIncludeInfraExcludesGates,
		RunCounterCountsClosedRows,
		RunCounterAnUnknownStatusMatchesNothing,
		RunCounterGroupsPartitionTheScalarSet,
		RunCounterLabelBucketsOverlapSoTotalIsNotTheirSum,
		RunCounterNamesTheEmptyBuckets,
		RunCounterPrefixesPriorityBuckets,
		RunCounterPriorityBucketsCountZeroAndCountEveryRow,
		RunCounterTheNoLabelBucketIsAbsentWhenEveryRowIsLabeled,
		RunCounterTypeBucketsAreTheRawTypeNames,
		RunCounterRefusesAnUnknownGroup,
		RunCounterNormalizesLabelsAndLeavesTheRequestAlone,
		RunCounterWritesNothing,
	),

	roleCases("CycleDetector", "CycleDetector()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *CycleDetectorFixture { return b.CycleDetector },
		RunCycleDetectorReportsNoCycleForAnAcyclicSubgraph,
		RunCycleDetectorFindsADurableCycleRotatedToItsLowestID,
		RunCycleDetectorReportsTheSameCyclesEveryRun,
		RunCycleDetectorMergesTheDurableAndEphemeralPlanes,
		RunCycleDetectorFollowsOnlyBlockingEdges,
		RunCycleDetectorReportsAnHonestPartial,
		RunCycleDetectorCountsAWhollyUndescribableCycle,
		RunCycleDetectorWritesNothing,
	),

	roleCases("Deleter", "Deleter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *DeleterFixture { return b.Deleter },
		RunDeleterRefusesAMalformedRequest,
		RunDeleterRefusesAnAbsentID,
		RunDeleterRefusesDependentsOutsideTheRequest,
		RunDeleterForceOrphansDependents,
		RunDeleterCascadeDeletesTheClosure,
		RunDeleterCascadeFromAWispRootDeletesTheClosure,
		RunDeleterGuardsAWispNamedWithADurableDependent,
		RunDeleterGuardsADurableNamedWithAWispDependent,
		RunDeleterCountsCrossPlaneEdgesItRemoves,
		RunDeleterNeverCallsALiveRowDeleted,
		RunDeleterErasesAcrossBothPlanes,
		RunDeleterCollapsesDuplicateIDs,
		RunDeleterRewritesReferencesInNeighbors,
		RunDeleterDryRunChangesNothing,
		RunDeleterRecordsAtMostOneHistoryEntry,
		RunDeleterDoesNotMutateTheCallerRequest,
		RunDeleterSettlesTheSurvivorsOfADeletedBlocker,
		RunDeleterSettlesTheChildrenOfADeletedParent,
		RunDeleterSettlesTheSurvivorsOfADeletedWispBlocker,
	),

	roleCases("DependencyEditor", "DependencyEditor()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *DependencyEditorFixture { return b.DependencyEditor },
		RunDependencyEditorRoutesWispSourcedEdgeToTheWispPlane,
		RunDependencyEditorMixedBatchWritesBothPlanes,
		RunDependencyEditorMixedBatchRefusalRollsBackBothPlanes,
		RunDependencyEditorRefusesCrossPlaneCycle,
		RunDependencyEditorAddedEchoesTheRequestOrder,
		RunDependencyEditorSameTypeReAddIsIdempotent,
		RunDependencyEditorRepeatsWithinOneRequestCollapse,
		RunDependencyEditorAttributesItsEventsToTheActor,
		RunDependencyEditorRetypeRefusalLeavesTheOriginalEdge,
		RunDependencyEditorRefusalWritesNothing,
		RunDependencyEditorRemoveIsIdempotent,
		RunDependencyEditorAppliesParentChildBeforeBlockingEdges,
		RunDependencyEditorAcceptsAnExternalTarget,
		RunDependencyEditorAcceptsAForeignRepoTarget,
		RunDependencyEditorRefusesBlockingEdgeAcrossItsOwnHierarchy,
		RunDependencyEditorRefusesSelfDependencyWithTheProbeSkipped,
		RunDependencyEditorRecordsOneHistoryEntryPerLandedRequest,
		RunDependencyEditorRecordsNoHistoryForAnAllEphemeralRequest,
		RunDependencyEditorSnapshotsTheRequest,
		RunDependencyEditorValidationRefusalsWriteNothing,
		RunDependencyEditorRoutesWispSourcedRemovalToTheWispPlane,
		RunDependencyEditorRefusesAGhostSource,
		RunDependencyEditorRefusesAMissingLocalTarget,
		RunDependencyEditorAcceptsATypeOutsideTheConstants,
		RunDependencyEditorRemovesOnlyTheNamedEdge,
		RunDependencyEditorSkipPerEdgeCycleCheckDropsOnlyTheProbe,
		RunDependencyEditorRecordsOneHistoryEntryForAMixedPlaneRequest,
		RunDependencyEditorWritesTheTargetIntoItsTypedColumn,
		RunDependencyEditorRefusesBlockingEdgeAcrossAWispHierarchy,
		RunDependencyEditorRefusesACycleThroughAParentChildHop,
		RunDependencyEditorRefusesASamePlaneEdgeClosingACrossPlaneCycle,
		RunDependencyEditorAddMarksItsSourceInTheSameVerb,
		RunDependencyEditorRemoveUnmarksItsSourceAndDescendants,
		RunDependencyEditorMaintainsBlockedStateAcrossPlanes,
		RunDependencyEditorClosedChildAddSatisfiesAnAnyChildrenGate,
	),

	roleCases("EdgeReader", "EdgeReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *EdgeReaderFixture { return b.EdgeReader },
		RunEdgeReaderAnswersOnePerAnchorInRequestOrder,
		RunEdgeReaderReportsAMissingAnchorRatherThanFailing,
		RunEdgeReaderDistinguishesNoEdgesFromNoAnchor,
		RunEdgeReaderReturnsTargetsVerbatim,
		RunEdgeReaderCollapsesRepeatedAnchors,
		RunEdgeReaderOrdersEdgesByTarget,
		RunEdgeReaderFiltersEdgesNotAnchors,
		RunEdgeReaderReadsBothPlanes,
		RunEdgeReaderResolvesExactIDsOnly,
		RunEdgeReaderAnswersAnEmptyRequest,
		RunEdgeReaderRefusesAnEmptyID,
		RunEdgeReaderRefusesAnUnusableType,
		RunEdgeReaderLeavesTheRequestAlone,
		RunEdgeReaderWritesNothing,
	),

	// Per case, not per role: see RoleContractBundle.IssueOperations.
	roleCases("IssueOperations", "IssueLifecycle()", oncePerCase,
		func(b RoleContractBundle) func(t *testing.T) *IssueOperationsStagingFixture { return b.IssueOperations },
		RunIssueOperationsCreateRoutesInfraTypesToWisps,
		RunIssueOperationsCreateRejectsMissingDependencyTargets,
		RunIssueOperationsCreateRefusesAnOccupiedID,
		RunIssueOperationsCreateRefusesAForeignIDPrefix,
		RunIssueOperationsUpdateMetadataPatchOrdersMergeSetUnset,
		RunIssueOperationsCreateInheritsParentLabels,
		RunIssueOperationsUpdateFoldsMetadataIntoOneEvent,
		RunIssueOperationsUpdateClosePolicy,
		RunIssueOperationsUpdateClosedFieldsMatchClose,
		RunIssueOperationsUpdateAssigneeTransferFence,
		RunIssueOperationsUpdateClaimConflictCarriesTheLosingState,
		RunIssueOperationsUpdateClaimHonorsConfiguredActiveStatuses,
		RunIssueOperationsUpdateIssuePlaneOnlyRefusesWisps,
		RunIssueOperationsUpdateLabelPatchOrdering,
		RunIssueOperationsUpdateLabelPatchValueRules,
		RunIssueOperationsUpdateParentIDReplacesTheParentEdge,
		RunIssueOperationsUpdateParentIDReplacesEveryParent,
		RunIssueOperationsUpdateMetadataReplaceClearsAndValidates,
		RunIssueOperationsRequestValuesAreNotMutated,
		RunIssueOperationsUpdateProvenanceLabelsHistory,
		RunIssueOperationsUpdatePersistentPreservesUnversionedClass,
		RunIssueOperationsUpdateConditionalGuardsGateOrdinaryEdits,
		RunIssueOperationsCreateWritesEveryScalarField,
		RunIssueOperationsUpdateWritesEveryScalarPatchField,
		RunIssueOperationsUpdateRefusesATypeOutsideTheWorkspaceVocabulary,
		RunIssueOperationsUpdateClaimIsAMutationWhenThePatchRestoresTheRow,
		RunIssueOperationsUpdateStatusCrossingSettlesDependers,
		RunIssueOperationsUpdateStatusCrossingSettlesAConditionalBlocksDepender,
		RunIssueOperationsCreateWithDependenciesSettlesInTheCreatingTransaction,
		RunIssueOperationsClaimLeavesBlockedStateAlone,
	),

	// The versioned-store pair, separately nil-able: see
	// RoleContractBundle.IssueOperationsStaging.
	roleCases("IssueOperationsStaging", "IssueLifecycle()", oncePerCase,
		func(b RoleContractBundle) func(t *testing.T) *IssueOperationsStagingFixture {
			return b.IssueOperationsStaging
		},
		RunIssueOperationsCreateReverseNonBlockingStagesConcreteTables,
		RunIssueOperationsCreateParentChildRecomputesWaitsForClosure,
	),

	roleCases("LifecycleCloseReopen", "IssueLifecycle()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *LifecycleCloseReopenFixture {
			return b.LifecycleCloseReopen
		},
		RunLifecycleCloseRefusalsCarryTheirTypesAndWriteNothing,
		RunLifecycleCloseAdmitsATransitivelyBlockedTarget,
		RunLifecycleCloseCountsOpenChildrenInBothPlanes,
		RunLifecycleCloseAdmitsAStaleBlockFlagWhoseBlockersHaveClosed,
		RunLifecycleCloseIsIdempotentOnAClosedRowThatStillLooksBlocked,
		RunLifecycleCloseIsIdempotentAndKeepsTheFirstClose,
		RunLifecycleCloseAndReopenKeepTheClaimHolder,
		RunLifecycleReopenLeavesNonDoneStatusesUnchanged,
		RunLifecycleCloseAndReopenSpanTheConfiguredDoneCategory,
		RunLifecycleExpectedVersionIsCheckedBeforeTheNoOps,
		RunLifecycleReopenRecordsItsReason,
		RunLifecycleResultsAreHydratedPostStateSnapshots,
		RunLifecycleCloseAndReopenRequireActorAndIssueID,
		RunLifecycleReopenProvenanceLabelsHistory,
		RunLifecycleCloseSettlesItsTransitiveAndCrossPlaneDependers,
		RunLifecycleCloseSettlesTheClosedRowItselfAndItsChild,
		RunLifecycleCloseOnASpawnersLastChildSatisfiesAWaitsForGate,
		RunLifecycleReopenReblocksItsDependers,
	),

	roleCases("LifecycleUpdate", "IssueLifecycle()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *LifecycleUpdateFixture { return b.LifecycleUpdate },
		RunLifecycleUpdatePersistsThePatchAndHydratesTheResult,
		RunLifecycleUpdateReportsNoChangeForASameValuePatch,
		RunLifecycleUpdateAppendsNotesWithoutReplacingThem,
		RunLifecycleUpdateClearsTheNullableMembers,
		RunLifecycleUpdateReplacesTheLabelSet,
		RunLifecycleUpdateResolvesBothPlanesUnlessRestricted,
		RunLifecycleUpdateRefusesUnknownIDsAndActorlessRequests,
		RunLifecycleUpdateRefusalWritesNoMemberOfThePatch,
	),

	roleCases("Memories", "Memories()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *MemoriesFixture { return b.Memories },
		RunMemoriesListOfAnEmptyPlaneAnswersAnEmptyMap,
		RunMemoriesRememberStoresContentVerbatim,
		RunMemoriesRememberDerivesTheKeyWhenAbsent,
		RunMemoriesRememberWithExplicitKeyStoresVerbatim,
		RunMemoriesRememberReplacesAndReportsIt,
		RunMemoriesRememberRefusesEmptyContent,
		RunMemoriesRememberRefusesAWhitespaceOnlyKey,
		RunMemoriesRememberRefusesAnUnderivableKey,
		RunMemoriesRecallAnswersTheStoredValue,
		RunMemoriesRecallReportsAMissAsNotFoundNotAnError,
		RunMemoriesRecallConflatesStoredEmptyWithAbsent,
		RunMemoriesForgetRemovesExactlyTheNamedRow,
		RunMemoriesForgetNeverTouchesTheSettingsPlane,
		RunMemoriesForgetReportsTheForgottenValue,
		RunMemoriesForgetOfAnAbsentKeyIsNotFoundAndDeletesNothing,
		RunMemoriesListReturnsOnlyTheMemoryPlane,
		RunMemoriesListSearchMatchesTheUserKeyNotTheStorageKey,
		RunMemoriesListSearchMatchesKeyOrValueCaseInsensitively,
		RunMemoriesARefusedWriteRecordsNoHistory,
	),

	roleCases("Querier", "Querier()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *QuerierFixture { return b.Querier },
		RunQuerierDisjunctionAnswersEveryMatch,
		RunQuerierPageIsAPrefixAndHasMoreIsExact,
		RunQuerierSortBoundsThePageInOrder,
		RunQuerierSortByTitleFoldsCaseBeforeItCutsThePage,
		RunQuerierSortByClosedPutsTheUnclosedRowsAtTheFarEnd,
		RunQuerierSortTieBreaksByIDInBothDirections,
		RunQuerierSortSeesTheWholeMatchingSet,
		RunQuerierHidesClosedUnlessTheExpressionOrTheFlagSaysOtherwise,
		RunQuerierRefusesAMalformedRequest,
		RunQuerierOffsetSkipsMatches,
		RunQuerierEmptyMatchIsAWellFormedPage,
		RunQuerierWritesNothing,
		RunQuerierDoesNotMutateTheCallerRequest,
	),

	roleCases("Reader", "IssueReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReaderFixture { return b.Reader },
		RunReaderReadyDefaultTypeExclusionsYieldToAnExplicitType,
		RunReaderReadyDeferredAndEphemeralGates,
		RunReaderReadyLimitBoundary,
		RunReaderOffsetSkipsTheRowsBeforeThePage,
		RunReaderReadySortPoliciesOrderTheSameRows,
		RunReaderListDefaultExclusionsAndTheirOverrides,
		RunReaderListRejectsATypeOutsideTheWorkspaceVocabulary,
		RunReaderListNaturalNumericIDSortTrimsAfterTheFetch,
		RunReaderListKeysetPositionResumesTheCreatedDescIDAscOrder,
		RunReaderListReadyFlagAnswersTheBlockerAwareSet,
		RunReaderListReadyFlagRefusesAFilterItCannotCarry,
		RunReaderListEmptyPageIsWellFormed,
		RunReaderListMaxRowsIsHonored,
		RunReaderListMaxRowsBoundaryIsLimitPlusOffset,
		RunReaderListSkipCountsDropsTheCardinalitiesAndNothingElse,
		RunReaderGetResolvesTheExactIDAcrossBothPlanes,
		RunReaderGetMissIsNotFoundAndBackendFailureDoesNotDecay,
		RunReaderGetOptionalRowListsAreOffByDefault,
		RunReaderGetDetailShapeMatchesTheSeededIssue,
		RunReaderDoesNotMutateTheCallerRequest,
		RunReaderListLimitBoundaryUnderASortTheDatabaseCanExpress,
		RunReaderReadySetOwnsItsStatusPinnedAndTemplateDecisions,
		RunReaderListReadyFlagCarriesTheAssigneeAndPriorityFilters,
		RunReaderListStatusAcceptsACommaSeparatedORSet,
	),

	roleCases("ReadyClaimer", "ReadyClaimer() and IssueReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReadyClaimerFixture { return b.ReadyClaimer },
		RunReadyClaimerRejectsLimitOffsetAndEmptyActor,
		RunReadyClaimerEmptyFrontIsNormal,
		RunReadyClaimerClaimsTheFrontRowAndReturnsThePostClaimState,
		RunReadyClaimerClaimsAnEphemeralRowTheFilterAdmits,
		RunReadyClaimerLeavesEphemeralRowsOutOfTheDefaultReadySet,
		RunReadyClaimerLeasesADurableWinButNotAnEphemeralOne,
		RunReadyClaimerAnswersTheQuestionReaderReadyLists,
		RunReadyClaimerSkipsIneligibleFrontRows,
		RunReadyClaimerRecordsOneHistoryEntryForAWin,
		RunReadyClaimerDoesNotMutateTheCallerRequest,
		RunReadyClaimerFencesTheClaimByEveryLabelSetAndTheParentItWasGiven,
		RunReadyClaimerHydratesOnlyItsBlocksEdgesIntoTheCardinalities,
	),

	roleCases("ReadyCounter", "ReadyCounter() and IssueReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReadyCounterFixture { return b.ReadyCounter },
		RunReadyCounterEqualsTheUnboundedPage,
		RunReadyCounterRejectsLimitAndOffset,
		RunReadyCounterCountsTheBlockerAwareSet,
		RunReadyCounterEphemeralGateMatchesTheListing,
		RunReadyCounterEmptyFrontIsZeroAndNil,
		RunReadyCounterWritesNothing,
		RunReadyCounterDoesNotMutateTheCallerRequest,
		RunReadyCounterCountsOnlyTheOpenRowsItsListingLists,
	),

	roleCases("Relations", "IssueRelations()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *RelationsFixture { return b.Relations },
		RunRelationsAnswersInThePinnedOrder,
		RunRelationsOrdersNeighborsFromBothPlanesTogether,
		RunRelationsAnswersAWispTargetInTheOutDirection,
		RunRelationsRefusesTheZeroDirection,
		RunRelationsSeparatesNoNeighborsFromNoSuchIssue,
		RunRelationsResolvesAWispAnchor,
		RunRelationsFiltersByAnOpenTypeVocabulary,
		RunRelationsRefusesAnUnusableTypeFilter,
		RunRelationsRefusesATypeFilterOverTheColumnLength,
		RunRelationsDirectionSelectsTheInverseGraph,
		RunRelationsLeavesTheCallersRequestAlone,
		RunRelationsLeavesAnExternalTargetOutOfTheAnswer,
		RunRelationsResolvesTheAnchorIDExactly,
	),

	roleCases("StatsReporter", "StatsReporter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *StatsReporterFixture { return b.StatsReporter },
		RunStatsReporterCountsEveryDurableRowByStatus,
		RunStatsReporterExcludesTheWispTier,
		RunStatsReporterAStatusOutsideTheTalliesIsCountedOnlyInTotal,
		RunStatsReporterBlockedCountsTheGraphNotTheStatus,
		RunStatsReporterBlockedExcludesByStatusNotByThePinnedFlag,
		RunStatsReporterBlockedCountsEveryUnfinishedStatusNotJustOpen,
		RunStatsReporterReadyIsOpenMinusBlocked,
		RunStatsReporterSkipBlockedPairsTheTwoPointers,
		RunStatsReporterExtendedFieldsAreAlwaysZero,
		RunStatsReporterWritesNothing,
		RunStatsReporterAssigneeStatsScopesToOneActor,
		RunStatsReporterAssigneeBlockedCountsTheStatusNotTheGraph,
		RunStatsReporterAssigneeStatsMergesTheWispTier,
		RunStatsReporterAssigneeStatsPopulatesBothPointers,
		RunStatsReporterAssigneeStatsRefusesAnEmptyAssignee,
	),

	roleCases("Sweeper", "Sweeper()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *SweeperFixture { return b.Sweeper },
		RunSweeperRefusesAnUnfilteredDurableSweep,
		RunSweeperRefusesAMalformedRequest,
		RunSweeperClearsOneTierAndLeavesTheOther,
		RunSweeperProtectsPinnedRows,
		RunSweeperHonorsTheCutoffAndThePattern,
		RunSweeperDryRunChangesNothing,
		RunSweeperProtectsRowsCitedFromAWispComment,
		RunSweeperProtectsCitedRows,
		RunSweeperEmptyMatchIsZeroAndNil,
		RunSweeperRecordsAtMostOneHistoryEntry,
		RunSweeperDoesNotMutateTheCallerRequest,
	),

	roleCases("TreeWalker", "TreeWalker()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *TreeWalkerFixture { return b.TreeWalker },
		RunTreeWalkerWalksTheDependenciesOfARoot,
		RunTreeWalkerWalksDependentsWhenAskedUp,
		RunTreeWalkerBoundsTheDescentAtMaxDepth,
		RunTreeWalkerTerminatesOnACycle,
		RunTreeWalkerRendersASharedSubtreeOnce,
		RunTreeWalkerMergesTheDurableAndEphemeralPlanes,
		RunTreeWalkerFollowsEveryTypeButRelatesTo,
		RunTreeWalkerPrunesEachHalfOfABothWalk,
		RunTreeWalkerAnswersBothDirectionsWithTheRootOnce,
		RunTreeWalkerPrunesByStatusKeepingAncestors,
		RunTreeWalkerPrunesEverythingWhenNothingMatches,
		RunTreeWalkerAnswersARootWithNoEdges,
		RunTreeWalkerRefusesAnAbsentRoot,
		RunTreeWalkerResolvesTheRootIDExactly,
		RunTreeWalkerCrossesPlanesFromAWispRootAndUpward,
		RunTreeWalkerRefusesAnInvalidRequest,
		RunTreeWalkerRefusesAWalkOverTheRowCap,
		RunTreeWalkerWritesNothing,
	),

	roleCases("VersionReconciler", "VersionReconciler()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *VersionReconcilerFixture { return b.VersionReconciler },
		RunVersionReconcilerRecordsAWorkspaceWithNoMarkers,
		RunVersionReconcilerAdvancesBothMarkersOnAnUpgrade,
		RunVersionReconcilerTreatsTheSameVersionAsANoOp,
		RunVersionReconcilerRefusesADowngradeWithoutAnError,
		RunVersionReconcilerRefusesAVersionBelowTheHighWaterMark,
		RunVersionReconcilerCatchesUpToTheHighWaterMark,
		RunVersionReconcilerRefusesAnEmptyVersion,
		RunVersionReconcilerLeavesTheMarkersStandingWhenItCannotComplete,
		RunVersionReconcilerRecordsNoHistory,
	),

	roleCases("WorkspaceConfig", "WorkspaceConfig()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *WorkspaceConfigFixture { return b.WorkspaceConfig },
		RunWorkspaceConfigStoresAValueVerbatim,
		RunWorkspaceConfigReplacesAnExistingValue,
		RunWorkspaceConfigConflatesAnUnsetKeyWithAnEmptyValue,
		RunWorkspaceConfigListsEveryStoredSetting,
		RunWorkspaceConfigListExcludesTheKVPlane,
		RunWorkspaceConfigUnsetRemovesTheSetting,
		RunWorkspaceConfigUnsetOfAnAbsentKeySucceeds,
		RunWorkspaceConfigRefusesAnEmptyKey,
		RunWorkspaceConfigRefusesTheProtectedKeyOnSet,
		RunWorkspaceConfigUnsetDoesNotRefuseTheProtectedKey,
		RunWorkspaceConfigRefusesAnUnparseableCustomStatus,
		RunWorkspaceConfigProjectsCustomStatuses,
		RunWorkspaceConfigProjectsCustomTypes,
		RunWorkspaceConfigUnsetLeavesTheProjectionBehind,
		RunWorkspaceConfigARefusedWriteRecordsNoHistory,
	),
}
